console.log('Si llegaste hasta aki felicidades, entra a los siguiente enlaces')
console.log('---------------------------------------')
console.log('https://boxvi.vercel.app/boris-quizhpe/')
console.log('---------------------------------------')
//console.log('https://wa.me/593996474990?text=Hola%20Boris,%20soy%20la%20ganadora%20del%20premio')
console.log('https://wa.me/593996474990')
console.log('---------------------------------------')
//console.log('recuerda, con la captura de pantalla de aki podras reclamar tu premio')
